// ********RoostGPT********
/*
Test generated by RoostGPT for test ReatAssured-Test using AI Type Open AI and AI Model gpt-4

Test generated for /api/customer/restaurantTable/create_post for http method type POST in rest-assured framework

RoostTestHash=6c5accfb60


*/

// ********RoostGPT********
package com.medeiros.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class createPostTest {
  
    @Test  
    public void createPost_Test() {  
        RestAssured.baseURI = System.getenv("BASE_URL");  
  
        // Read CSV file  
        try (BufferedReader reader = new BufferedReader(new FileReader("src" + File.separator + "test" + File.separator + "java" + File.separator + "com" + File.separator + "medeiros" + File.separator + "RoostTest" + File.separator + "createPostTest.csv"))) {  
            String headerLine = reader.readLine();  
            String[] headers = headerLine.split(",");  
  
            String line;  
            while ((line = reader.readLine()) != null) {  
                String[] data = line.split(",");  
  
                // Create a map of header to data  
                Map<String, String> map = new HashMap<>();  
                for (int i = 0; i < headers.length; i++) {  
                    map.put(headers[i], data[i]);  
                }  
                
  
                Response response = given()
				.queryParam("company", map.get("company") != null ? map.get("company") : "")
				.queryParam("tableGroupId", map.get("tableGroupId") != null ? map.get("tableGroupId") : "")
				.queryParam("number", map.get("number") != null ? map.get("number") : "")
				.queryParam("name", map.get("name") != null ? map.get("name") : "")
				.header("Authorization", "Bearer " + System.getenv("AUTH_TOKEN"))
                .when()
                .post("/api/customer/restaurantTable/create")  
                .then() 
                .extract().response();    
         
                if (response.statusCode() == 200) {
					System.out.println("Description: Create new Restaurant Table");
      
              if (response.jsonPath().get("id") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("id"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("external_id") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("external_id"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("number") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("number"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("name") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("name"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("restaurant_table_group_id") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("restaurant_table_group_id"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("updated_at") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("updated_at"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("created_at") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("created_at"), instanceOf(String.class));  
          }
				}
  
            }  
        } catch (IOException e) {  
            e.printStackTrace();  
        }  
    }
}
