// ********RoostGPT********
/*
Test generated by RoostGPT for test ReatAssured-Test using AI Type Open AI and AI Model gpt-4

Test generated for /scheduled-payments_get for http method type GET in rest-assured framework

RoostTestHash=1524859f27


*/

// ********RoostGPT********
package com.medeiros.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class scheduledpaymentsGetTest {
  
    @Test  
    public void scheduledpaymentsGet_Test() {  
        RestAssured.baseURI = System.getenv("BASE_URL");  
  
        // Read CSV file  
        try (BufferedReader reader = new BufferedReader(new FileReader("src" + File.separator + "test" + File.separator + "java" + File.separator + "com" + File.separator + "medeiros" + File.separator + "RoostTest" + File.separator + "scheduled-paymentsGetTest.csv"))) {  
            String headerLine = reader.readLine();  
            String[] headers = headerLine.split(",");  
  
            String line;  
            while ((line = reader.readLine()) != null) {  
                String[] data = line.split(",");  
  
                // Create a map of header to data  
                Map<String, String> map = new HashMap<>();  
                for (int i = 0; i < headers.length; i++) {  
                    map.put(headers[i], data[i]);  
                }  
                
  
                Response response = given()
                .header("Authorization", "Bearer " + System.getenv("BEARER_TOKEN"))
                .header("x-fapi-financial-id", map.get("x-fapi-financial-id") != null ? map.get("x-fapi-financial-id") : "")
                .when()
                .get("/scheduled-payments")  
                .then() 
                .extract().response();    
         
                if (response.statusCode() == 200) {
					System.out.println("Description: Scheduled Payments Read");
      
              if (response.jsonPath().get("Data") != null) {      
              if (response.jsonPath().get("Data.ScheduledPayment") != null) {      
                for (int i = 0; i < response.jsonPath().getList("Data.ScheduledPayment").size(); i++) {      
              if (response.jsonPath().get("Data.ScheduledPayment["+ i +"].AccountId") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Data.ScheduledPayment["+ i +"].AccountId"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].AccountId").length(), lessThanOrEqualTo(40));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].AccountId").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Data.ScheduledPayment["+ i +"].ScheduledPaymentId") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Data.ScheduledPayment["+ i +"].ScheduledPaymentId"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].ScheduledPaymentId").length(), lessThanOrEqualTo(40));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].ScheduledPaymentId").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Data.ScheduledPayment["+ i +"].ScheduledPaymentDateTime") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Data.ScheduledPayment["+ i +"].ScheduledPaymentDateTime"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("Data.ScheduledPayment["+ i +"].ScheduledType") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Data.ScheduledPayment["+ i +"].ScheduledType"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].ScheduledType"), anyOf(equalTo("Arrival"), equalTo("Execution")));
  
          }
      
              if (response.jsonPath().get("Data.ScheduledPayment["+ i +"].Reference") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Data.ScheduledPayment["+ i +"].Reference"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].Reference").length(), lessThanOrEqualTo(35));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].Reference").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Data.ScheduledPayment["+ i +"].InstructedAmount") != null) {      
              if (response.jsonPath().get("Data.ScheduledPayment["+ i +"].InstructedAmount.Amount") != null) {    
                // MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].InstructedAmount.Amount"), matchesPattern("^\\d{1,13}\\.\\d{1,5}$")); 
  
                MatcherAssert.assertThat(response.jsonPath().get("Data.ScheduledPayment["+ i +"].InstructedAmount.Amount"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("Data.ScheduledPayment["+ i +"].InstructedAmount.Currency") != null) {    
                // MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].InstructedAmount.Currency"), matchesPattern("^[A-Z]{3,3}$")); 
  
                MatcherAssert.assertThat(response.jsonPath().get("Data.ScheduledPayment["+ i +"].InstructedAmount.Currency"), instanceOf(String.class));  
          }
  
          }
      
              if (response.jsonPath().get("Data.ScheduledPayment["+ i +"].CreditorAgent") != null) {      
              if (response.jsonPath().get("Data.ScheduledPayment["+ i +"].CreditorAgent.SchemeName[0]") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Data.ScheduledPayment["+ i +"].CreditorAgent.SchemeName[0]"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].CreditorAgent.SchemeName[0]").length(), lessThanOrEqualTo(40));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].CreditorAgent.SchemeName[0]").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Data.ScheduledPayment["+ i +"].CreditorAgent.Identification") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Data.ScheduledPayment["+ i +"].CreditorAgent.Identification"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].CreditorAgent.Identification").length(), lessThanOrEqualTo(35));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].CreditorAgent.Identification").length(), greaterThanOrEqualTo(1));
  
          }
  
          }
      
              if (response.jsonPath().get("Data.ScheduledPayment["+ i +"].CreditorAccount") != null) {      
              if (response.jsonPath().get("Data.ScheduledPayment["+ i +"].CreditorAccount.SchemeName[0]") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Data.ScheduledPayment["+ i +"].CreditorAccount.SchemeName[0]"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].CreditorAccount.SchemeName[0]").length(), lessThanOrEqualTo(40));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].CreditorAccount.SchemeName[0]").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Data.ScheduledPayment["+ i +"].CreditorAccount.Identification") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Data.ScheduledPayment["+ i +"].CreditorAccount.Identification"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].CreditorAccount.Identification").length(), lessThanOrEqualTo(256));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].CreditorAccount.Identification").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Data.ScheduledPayment["+ i +"].CreditorAccount.Name") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Data.ScheduledPayment["+ i +"].CreditorAccount.Name"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].CreditorAccount.Name").length(), lessThanOrEqualTo(70));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].CreditorAccount.Name").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Data.ScheduledPayment["+ i +"].CreditorAccount.SecondaryIdentification") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Data.ScheduledPayment["+ i +"].CreditorAccount.SecondaryIdentification"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].CreditorAccount.SecondaryIdentification").length(), lessThanOrEqualTo(34));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Data.ScheduledPayment["+ i +"].CreditorAccount.SecondaryIdentification").length(), greaterThanOrEqualTo(1));
  
          }
  
          }
      
                  }    
                MatcherAssert.assertThat(response.jsonPath().getList("Data.ScheduledPayment"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.jsonPath().get("Links") != null) {      
              if (response.jsonPath().get("Links.Self") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Links.Self"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("Links.First") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Links.First"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("Links.Prev") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Links.Prev"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("Links.Next") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Links.Next"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("Links.Last") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Links.Last"), instanceOf(String.class));  
          }
  
          }
      
              if (response.jsonPath().get("Meta") != null) {      
              if (response.jsonPath().get("Meta.TotalPages") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Meta.TotalPages"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("Meta.FirstAvailableDateTime") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Meta.FirstAvailableDateTime"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("Meta.LastAvailableDateTime") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Meta.LastAvailableDateTime"), instanceOf(String.class));  
          }
  
          }
				}
if (response.statusCode() == 400) {
					System.out.println("Description: Bad request");
      
              if (response.jsonPath().get("Code") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Code"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Code").length(), lessThanOrEqualTo(40));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Code").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Id") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Id"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Id").length(), lessThanOrEqualTo(40));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Id").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Message") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Message"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Message").length(), lessThanOrEqualTo(500));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Message").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Errors") != null) {      
                for (int i = 0; i < response.jsonPath().getList("Errors").size(); i++) {      
              if (response.jsonPath().get("Errors["+ i +"].ErrorCode") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Errors["+ i +"].ErrorCode"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Errors["+ i +"].ErrorCode").length(), lessThanOrEqualTo(128));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Errors["+ i +"].ErrorCode").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Errors["+ i +"].Message") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Errors["+ i +"].Message"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Errors["+ i +"].Message").length(), lessThanOrEqualTo(500));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Errors["+ i +"].Message").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Errors["+ i +"].Path") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Errors["+ i +"].Path"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Errors["+ i +"].Path").length(), lessThanOrEqualTo(500));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Errors["+ i +"].Path").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Errors["+ i +"].Url") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Errors["+ i +"].Url"), instanceOf(String.class));  
          }
      
                  }    
                MatcherAssert.assertThat(response.jsonPath().getList("Errors"), instanceOf(List.class));
  
          }
				}
if (response.statusCode() == 401) {
					System.out.println("Description: Unauthorized");
				}
if (response.statusCode() == 403) {
					System.out.println("Description: Forbidden");
				}
if (response.statusCode() == 404) {
					System.out.println("Description: Not found");
				}
if (response.statusCode() == 405) {
					System.out.println("Description: Method Not Allowed");
				}
if (response.statusCode() == 406) {
					System.out.println("Description: Not Acceptable");
				}
if (response.statusCode() == 429) {
					System.out.println("Description: Too Many Requests");
				}
if (response.statusCode() == 500) {
					System.out.println("Description: Internal Server Error");
      
              if (response.jsonPath().get("Code") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Code"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Code").length(), lessThanOrEqualTo(40));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Code").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Id") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Id"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Id").length(), lessThanOrEqualTo(40));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Id").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Message") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Message"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Message").length(), lessThanOrEqualTo(500));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Message").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Errors") != null) {      
                for (int i = 0; i < response.jsonPath().getList("Errors").size(); i++) {      
              if (response.jsonPath().get("Errors["+ i +"].ErrorCode") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Errors["+ i +"].ErrorCode"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Errors["+ i +"].ErrorCode").length(), lessThanOrEqualTo(128));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Errors["+ i +"].ErrorCode").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Errors["+ i +"].Message") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Errors["+ i +"].Message"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Errors["+ i +"].Message").length(), lessThanOrEqualTo(500));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Errors["+ i +"].Message").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Errors["+ i +"].Path") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Errors["+ i +"].Path"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("Errors["+ i +"].Path").length(), lessThanOrEqualTo(500));
  
                MatcherAssert.assertThat(response.jsonPath().getString("Errors["+ i +"].Path").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.jsonPath().get("Errors["+ i +"].Url") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("Errors["+ i +"].Url"), instanceOf(String.class));  
          }
      
                  }    
                MatcherAssert.assertThat(response.jsonPath().getList("Errors"), instanceOf(List.class));
  
          }
				}
  
            }  
        } catch (IOException e) {  
            e.printStackTrace();  
        }  
    }
}
