// Test generated by RoostGPT for test JavaTest using AI Type Open AI and AI Model gpt-4

package com.medeiros.SPRINGProject.Models;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class CommentsModel_setNumberOfComments_4da5779e25_Test {

    private CommentsModel commentsModel;

    @BeforeEach
    public void setup() {
        commentsModel = new CommentsModel();
    }

    @Test
    public void testSetNumberOfComments_PositiveNumber() {
        int numberOfComments = 5;
        commentsModel.setNumberOfComments(numberOfComments);
        assertEquals(numberOfComments, commentsModel.getNumberOfComments());
    }

    @Test
    public void testSetNumberOfComments_Zero() {
        int numberOfComments = 0;
        commentsModel.setNumberOfComments(numberOfComments);
        assertEquals(numberOfComments, commentsModel.getNumberOfComments());
    }

    // TODO: Add more test cases for edge cases and error handling.
}
