// Test generated by RoostGPT for test JavaTest using AI Type Open AI and AI Model gpt-4

package com.medeiros.SPRINGProject.Models;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.InjectMocks;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class CommentsModel_setComment_7661a4acb2_Test {

    @InjectMocks
    private CommentsModel commentsModel;

    @BeforeEach
    public void setUp() {
        commentsModel = new CommentsModel();
    }

    @Test
    public void testSetComment() {
        String comment = "This is a test comment";
        commentsModel.setComment(comment);
        assertEquals(comment, commentsModel.getComment());
    }

    @Test
    public void testSetCommentWithEmptyString() {
        String comment = "";
        commentsModel.setComment(comment);
        assertEquals(comment, commentsModel.getComment());
    }
}
