// Test generated by RoostGPT for test JavaTest using AI Type Open AI and AI Model gpt-4

package com.medeiros.SPRINGProject.Models;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class CommentsModel_getNumberOfComments_586e635c5c_Test {

    @Mock
    private CommentsModel commentsModel;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetNumberOfCommentsSuccess() {
        when(commentsModel.getNumberOfComments()).thenReturn(5);

        int actual = commentsModel.getNumberOfComments();
        int expected = 5;

        assertEquals(expected, actual, "Expected number of comments did not match actual number of comments");
    }

    @Test
    public void testGetNumberOfCommentsZero() {
        when(commentsModel.getNumberOfComments()).thenReturn(0);

        int actual = commentsModel.getNumberOfComments();
        int expected = 0;

        assertEquals(expected, actual, "Expected number of comments did not match actual number of comments");
    }
}
