// Test generated by RoostGPT for test JavaTest using AI Type Open AI and AI Model gpt-4

package com.medeiros.SPRINGProject.Models;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class CommentsModel_getComment_27b11f0cce_Test {

    @InjectMocks
    private CommentsModel commentsModel;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetComment_success() {
        String expectedComment = "This is a test comment";
        commentsModel.setComment(expectedComment);
        String actualComment = commentsModel.getComment();

        assertNotNull(actualComment, "Comment should not be null");
        assertEquals(expectedComment, actualComment, "Expected and actual comments should match");
    }

    @Test
    public void testGetComment_empty() {
        String expectedComment = "";
        commentsModel.setComment(expectedComment);
        String actualComment = commentsModel.getComment();

        assertNotNull(actualComment, "Comment should not be null");
        assertEquals(expectedComment, actualComment, "Expected and actual comments should match");
    }
}
