// Test generated by RoostGPT for test JavaTest using AI Type Open AI and AI Model gpt-4

package com.medeiros.SPRINGProject.Controllers;

import com.medeiros.SPRINGProject.Models.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import java.util.Arrays;
import java.util.List;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class ForumController_showMessages_778e9dc544_Test {

    @InjectMocks
    private ForumController forumController;

    @Mock
    private ForumChatRepository ChatRepository;

    @Test
    public void testShowMessagesSuccess() {
        ForumChatModel message1 = new ForumChatModel("Hello", 1, 1);
        ForumChatModel message2 = new ForumChatModel("Hi", 2, 1);
        List<ForumChatModel> messages = Arrays.asList(message1, message2);

        when(ChatRepository.findAll()).thenReturn(messages);

        Iterable<ForumChatModel> returnedMessages = forumController.showMessages();

        assertNotNull(returnedMessages);
    }

    @Test
    public void testShowMessagesNoMessages() {
        when(ChatRepository.findAll()).thenReturn(null);

        Iterable<ForumChatModel> returnedMessages = forumController.showMessages();

        assertNotNull(returnedMessages);
    }
}
