// Test generated by RoostGPT for test JavaTest using AI Type Open AI and AI Model gpt-4

package com.medeiros.SPRINGProject.Controllers;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.medeiros.SPRINGProject.Models.UserAccRepo;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

@SpringBootTest
public class UserAccountController_deleteUserById_91ecd15d81_Test {

    @MockBean
    private UserAccRepo userAccRepo;

    private UserAccountController userAccountController;

    @BeforeEach
    void setUp() {
        userAccountController = new UserAccountController(userAccRepo);
    }

    @Test
    public void testDeleteUserById_ValidId() {
        String ID = "1";
        when(userAccRepo.existsById(Integer.parseInt(ID))).thenReturn(true);

        String result = userAccountController.deleteUserById(ID);
        assertEquals("Conta Deletada", result);

        verify(userAccRepo, times(1)).deleteById(Integer.parseInt(ID));
    }

    @Test
    public void testDeleteUserById_InvalidId() {
        String ID = "99999";
        when(userAccRepo.existsById(Integer.parseInt(ID))).thenReturn(false);

        String result = userAccountController.deleteUserById(ID);
        assertEquals("Conta Deletada", result);

        verify(userAccRepo, times(1)).deleteById(Integer.parseInt(ID));
    }
}
